### ISSUE TITLE
ILS Gone on the NAVRAD 

### ISSUE THREAD

**Issue by RGaming007** [YesAviation/747-400#25] opened 2020-06-02 18:35 UTC
![X-Plane Screenshot 2020 06 02 - 14 32 25 89](https://user-images.githubusercontent.com/60050366/83556680-57be3680-a4de-11ea-9925-ccafeb527349.png)

**Comment by mSparks43** [comment] 2020-06-03 01:01
its not working exactly as intended yet (some airports tuning wrong)
but it does become active when an ils approach is programmed into the fmc and will set the nav radios to that ils when the app button is pressed.

You can also tune them manually from the acars->vhf fmc page.

**Comment by mSparks43** [comment] 2020-06-11 16:42
closing this issue as resolved, if it persists please reopen, open a different issue for any related problems

**Closed by mSparks43** 2020-06-11 16:42 UTC
